name: Run test with cicd

on: [ push ]

jobs:
  build_and_run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test with pytest
        env:
          CLIENT_SLACK: ${{ secrets.CLIENT_SLACK }}
          API_KEY_QASE: ${{ secrets.API_KEY_QASE }}
        run: pytest

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './report'
          github-token: ${{ secrets.MY_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

      - name: Get deployment URL
        id: deployment
        uses: dorshinar/get-deployment-url@master
        timeout-minutes: 5
        with:
          token: ${{ secrets.MY_TOKEN }}

      - name: Send Report Slack
        run: python setting/netlify_link.py
        env:
          deployment: ${{ steps.deployment.outputs.deployment }}
          CLIENT_SLACK: ${{ secrets.CLIENT_SLACK }}